{% set data=load_setup_py_data() %}

package:
  name: joint-calling
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - hail
  run:
    - python
    - hail
    - click
    - pandas
    - google-cloud-sdk
    - google-cloud-storage
    - gnomad
    - fsspec  # for reading files from Google Cloud Storage
    - gcsfs >=0.3.0  # for reading files from Google Cloud Storage

test:
  commands:
    - sample_qc.py --version
    - combine_gvcfs.py --version
    - mt_to_vcf.py --version

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
