name: PyPI
on:
  push:
    branches:
      - main
      - develop
jobs:
  pypi:
    runs-on: ubuntu-latest
    env:
      package: "${{ github.event.repository.name }}"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version
        run: |
          bump2version sha --no-commit --allow-dirty \
          --new-version "$(python setup.py --version).dev${GITHUB_SHA::8}"

      - name: Print new version
        run: |
          cat setup.py
          python setup.py --version

      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          build: true
          upload: true
