name: Test Upload Processor
on: [push]
jobs:
  Test-Upload-Processor:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_IMAGE: australia-southeast1-docker.pkg.dev/vivian-dev/images/driver:ece767c87103
      GSA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "fewgenomes"
          service_account_key: "${{ secrets.GCP_SA_KEY }}"

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: "test upload processor"
        run: |
          TOKEN=$(gcloud auth print-identity-token)
          $URL ='https://server-a2pko7ameq-ts.a.run.app'
          curl --fail --silent --show-error -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type:application/json" \
            -d '{"output": "gs://cpg-fewgenomes-temporary/upload-main", "dataset": "fewgenomes", "accessLevel": "test", "repo": "fewgenomes", "commit": "${{ github.sha }}", "cwd": null, "script": ["test/test_upload_processor.py], "description": "test-file", "wait": true}' \
            $URL
